### ISSUE TITLE
Fix for those who need to left justify their page indicator

### ISSUE THREAD

**Issue by SteveG-MATTR** [kolking/react-native-page-indicator#21]
Deleted

**Comment by kolking** [comment]
Hey Steve! Thanks for writing the issue. Not sure why have you deleted it. Despite the fact the proposed fix isn't correct, the morse indicator's align issue need to be resolved. I'll do my best to fix it asap and will let you know.

**Comment by kolking** [comment]
Should be fixed in the latest v2.3.0, I'd appreciate if you could test the new version and let me know.
