### ISSUE TITLE
Programmatically trigger with button

### ISSUE THREAD

**Issue by MariuzM** [kolking/react-native-page-indicator#26]
Is there a way to programmatically trigger with button but also keep the scroll / swipe functionality? Sorry if i missed this in docs.

**Comment by kolking** [comment]
Hey Marius! Could you clarify what do you mean by "trigger with button"? Trigger what? :)

**Comment by MariuzM** [comment]
Sure, sorry, basically when i want to go to `Next Page` i do swipe, but i also want to add button at bottom saying `Next Page`, by clicking that it will swipe to `Next Page` but without me actually doing hand gestures.

**Comment by kolking** [comment]
Ah, got it now. Sure you can do that programmatically. But note that the page indicator is not involved in this process, there is no functionality to change pages, it just displays the active slide/page that you passed to the component via the `current` prop.
