### ISSUE TITLE
Can we have props to increase size of inactive page indicators?

### ISSUE THREAD

**Issue by vijaykumariorbit** [kolking/react-native-page-indicator#3]

**Comment by kolking** [comment]
@vijaykumariorbit sure, there is the `size` prop. Refer to the [list of props](https://github.com/kolking/react-native-page-indicator#props) for more information.

**Comment by vijaykumariorbit** [comment]
Thanks @kolking  Actually I am aware of `size ` props and already using the same.
But what I actually want is, the active page and inactive page indicators are of different lengths. 
Is there a possible way to have both active and inactive indicators with same length?

**Comment by kolking** [comment]
@vijaykumariorbit I have recently released version 2.0.0, which allows you to create indicators of equal length by setting the `variant` prop to `train` and controlling the length using the `dashSize` prop.

You're welcome to try the new version. Take a look at the [updated Readme](https://github.com/kolking/react-native-page-indicator/#readme) for details.

Closing the issue as resolved.
